# Generated by Django 3.2.9 on 2021-12-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_cadastro_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionarVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.usuario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.veiculo')),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
