# Generated by Django 3.2.9 on 2021-12-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_auto_20211201_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdicionarVeiculo',
        ),
    ]
