# Generated by Django 3.2.9 on 2021-12-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_delete_adicionarveiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
    ]
