# Generated by Django 3.2.9 on 2021-12-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_remove_usuario_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
