# Generated by Django 3.2.9 on 2021-12-02 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0010_servicorealizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome',
            new_name='servico',
        ),
        migrations.AlterField(
            model_name='servicorealizado',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 21, 26, 10, 986655)),
        ),
    ]
