# Generated by Django 3.2.9 on 2021-12-02 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0011_auto_20211201_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='servico',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='servicorealizado',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 21, 29, 40, 433288)),
        ),
    ]
