# Generated by Django 3.2.9 on 2021-12-02 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0012_auto_20211201_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicorealizado',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 22, 15, 56, 76378)),
        ),
    ]
