# Generated by Django 3.2.9 on 2021-12-03 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0013_alter_servicorealizado_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='servicorealizado',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 9, 49, 49, 144544)),
        ),
    ]
