# Generated by Django 3.2.9 on 2021-12-03 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0015_auto_20211203_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 19, 25, 31, 711946)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.funcionario'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.cliente'),
        ),
    ]
