# Generated by Django 3.2.9 on 2021-12-03 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0016_auto_20211203_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 19, 34, 21, 65566)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.CharField(max_length=30),
        ),
    ]
