# Generated by Django 3.2.9 on 2021-12-03 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0019_auto_20211203_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 20, 19, 7, 684228)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.IntegerField(verbose_name='valor'),
        ),
    ]
