# Generated by Django 3.2.9 on 2021-12-03 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0020_auto_20211203_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 20, 21, 21, 586871)),
        ),
    ]
