# Generated by Django 3.2.9 on 2021-12-04 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0024_auto_20211204_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 4, 1, 4, 5, 625449)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
