# Generated by Django 3.2.9 on 2021-12-04 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0025_auto_20211204_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 4, 17, 17, 16, 626757)),
        ),
    ]
