# Generated by Django 3.2.9 on 2021-12-05 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0027_auto_20211205_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 5, 12, 25, 3, 481049)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
