# Generated by Django 3.2.9 on 2021-12-05 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0029_auto_20211205_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 5, 12, 30, 2, 550563)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
