# Generated by Django 3.2.9 on 2021-12-06 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0037_auto_20211206_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 6, 8, 45, 42, 801593)),
        ),
    ]
